name: base
dependencies:
  - pytorch=0.4.1
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - nltk
  - requests
  - click
  - flask
  - termcolor
  - regex
  - tqdm
  - pexpect==4.2.1
channels:
  - pytorch
